---
name: Pull Requests

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master
env:
  DOCKER_BUILDCONTEXT: '.'
  DOCKER_FILEPATH: 'Dockerfile'
  DOCKER_IMAGE: ${{ github.event.repository.name }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/${{ env.DOCKER_IMAGE }}
          path: ${{ env.DOCKER_BUILDCONTEXT }}
          dockerfile: ${{ env.DOCKER_FILEPATH }}
          push: false

